### ISSUE TITLE
model confusion

### ISSUE THREAD

**Issue by BruceRussll** [cuiziteng/Aleth-NeRF#12]
Hi, thank you for your great work. But I'm confused about these models, could you explain them please?
Thanks.
![image](https://github.com/cuiziteng/Aleth-NeRF/assets/136967211/8069a4d3-60fe-4ec1-a921-9c5457a436b4)

**Comment by cuiziteng** [comment]
Hi, thanks so much for your interests. 

Due to our project is built on the toolbox, https://github.com/kakaobrain/nerf-factory, these code also direct from here. 

But have no relationship with Aleth-NeRF, only "aleth_nerf" and "aleth_nerf_exp" related to our project.

**Comment by BruceRussll** [comment]
Thank you, I wonder what the difference between "aleth_nerf" and "aleth_nerf_exp".

**Comment by cuiziteng** [comment]
"aleth_nerf" is the Aleth-NeRF for low-light conditions and "aleth_nerf_exp" is Aleth-NeRF for over-exposure conditions, they are separate because there are some different loss setting and model setting for low-light & over-exposure conditions.

**Comment by BruceRussll** [comment]
I understand. Thank you very much!
