### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by ShenZheng2000** [cuiziteng/Aleth-NeRF#16]
How many GPUs do you use for training, and how many hours does it take to converge the model?

**Comment by cuiziteng** [comment]
Hi, thanks for your interest in our work !

I use 4 GPUs for training the model, in fact 2 GPUs is also enough, and the converge time is around >= 1 hour.  

We set the steps in 62500 and 12500 is an epoch, I think 25000 (2 epochs) is also enough for converge. But the results maybe not as good as 62500 (5 epochs).
