### ISSUE TITLE
How to make the gif in your website

### ISSUE THREAD

**Issue by XLR-man** [cuiziteng/Aleth-NeRF#17]
I just want to know how to make the gif in your website？Is it made with images rendered from all training viewpoints？Or is it from custom viewpoints? Is there any detailed code for this?

**Comment by cuiziteng** [comment]
Hi, thanks for you interest, just add the --ginb run.run_render=True in test time.

<img width="899" alt="image" src="https://github.com/cuiziteng/Aleth-NeRF/assets/55396225/37393378-5b73-40fe-a594-743c40101839">

And the viewpoint (camera point) range is shown in 
https://github.com/cuiziteng/Aleth-NeRF/blob/758060c3cbd1d37fa6406c542f2a0f9b82fd52df/src/data/data_util/blender.py#L126

**Comment by XLR-man** [comment]
Thank you!
So if i have other custom datasets, can I use these code without any change

**Comment by XLR-man** [comment]
And what I want to ask is, how do you do Image Enhance + NeRF? Is the enhancement pre-processing or post-processing, because it looks like post-processing according to the predict process?

**Comment by cuiziteng** [comment]
Image Enhance + NeRF means pre-processing, NeRF + Enhance means post-processing, we do the both in our paper ~

And for your own dataset I think you need to adjust that camera angle to get video.

**Comment by XLR-man** [comment]
I mean, in your website, the viewpoints of Image Enhance + NeRF is same as the Aleth NeRF.  I am confused that how it work, because you need to have render poses first and this moment it only has rays info, then through NeRF to render the dark and enhanced results. How it get Ehancement of this render poses through 2D methods first?

**Comment by cuiziteng** [comment]
In the training time, the NeRF trained on enhanced views, in the test time, the novel view's camera pose would input to NeRF to get rendering results, it is same as vanilla NeRF, the only differents is training images be enhanced.
