### ISSUE TITLE
About color deviation between test results and GT

### ISSUE THREAD

**Issue by w-k-g** [cuiziteng/Aleth-NeRF#18]
Thank you for your greate work.

I am trying to replicating your project and I found there is color shift between the rendered images and your presented results in the paper. The results in the paper looks great. I am wondering if you received the results by using the hyperparameters specified in _configs_ directory.

thanks.

**Comment by cuiziteng** [comment]
Yes, the default results in paper is generated by con = 10 and eta = 0.4

**Comment by w-k-g** [comment]
Appreciate it! And congratulations!

**Comment by cuiziteng** [comment]
Thanks!
