### ISSUE TITLE
How the low lighting and exposure of the synthetic dataset are made

### ISSUE THREAD

**Issue by 520jz** [cuiziteng/Aleth-NeRF#20]
Hello, I would like to know how this low light and exposure effect of the dataset is made, is there a script for the relevant transformations?
For example:
![1](https://github.com/cuiziteng/Aleth-NeRF/assets/125104736/bb7a6847-38aa-45af-998d-f19fa7db0efc)
![1](https://github.com/cuiziteng/Aleth-NeRF/assets/125104736/3ea2681f-5b69-4a4e-8d8c-0f966d67cfe0)

**Comment by cuiziteng** [comment]
Hello, I collect the real-world pair dataset by changing the exposure time and ISO value in camera,.

If you want to synthesis images, maybe you can try some gamma correction related image process.
