### ISSUE TITLE
About graphing curvilinear relations

### ISSUE THREAD

**Issue by BruceRull** [cuiziteng/Aleth-NeRF#21]
Hi, thank you for your great work. I would like to know how to output the following two relationship diagrams. Could you please help me?
![03BC Y}95N}~_I3NNAV~X$6](https://github.com/cuiziteng/Aleth-NeRF/assets/165174674/bcdd6e2c-1738-4a33-b139-04933ec776a4)

**Comment by cuiziteng** [comment]
Hi, thanks for the question, the Fig shows the distribution relationship between concealing field and density, higher density denotes the 3D particle location exist object while lower density denotes the 3D particle location do not exist object. 

In Aleth-NeRF training we found that the concealing field tends to generate at the lower density place (have negative relation, Corr, with density), which means concealing field are tends to generate at air.

**Comment by BruceRull** [comment]
Thank you for your patience. How do you implement this with code?

**Comment by cuiziteng** [comment]
Hello, this part is as visualization to show the relationship between concealing fields and density, we didn't add some additional constrain in our code.
