### ISSUE TITLE
depth

### ISSUE THREAD

**Issue by Willamare** [cuiziteng/Aleth-NeRF#27]
Hello, what methods are used to generate depth maps?

**Comment by cuiziteng** [comment]
Hi, the gray-scale depth maps can be directly generated during test stage, while the pseudo-color depth maps can be translated from [https://github.com/cuiziteng/Aleth-NeRF/blob/master/depth_trans.py](https://github.com/cuiziteng/Aleth-NeRF/blob/master/depth_trans.py).
