### ISSUE TITLE
数据集采集方式

### ISSUE THREAD

**Issue by JaysonWangElite** [cuiziteng/Aleth-NeRF#28]
作者您好！首先祝贺您中AAAI！优秀的工作！
我的问题是：数据在低曝光、正常曝光、过曝光三种方式是怎样保持视角一致性的？请问是固定机位进行分时段采集，还是在同一时段直接调节相机曝光参数进行采集的？

**Comment by cuiziteng** [comment]
非常感谢您的关注，是后者，固定机位同一时段直接调节相机曝光参数进行采集的
