### ISSUE TITLE
how to train on my own dataset

### ISSUE THREAD

**Issue by Sun-Gaust** [cuiziteng/Aleth-NeRF#29]
hello ,could you please tell me the way to train my own dataset? The results seem not right, is there something I might be overlooking.
Additionally, if I want to train a 360-degree dataset, what adjustments do I need to make?
![image](https://github.com/user-attachments/assets/469bcdf3-8d20-4793-abd9-07c70c4a28e4)
![image](https://github.com/user-attachments/assets/6e2ecb1b-17d2-4138-8df0-132c471a1e43)

**Comment by cuiziteng** [comment]
Thank you for your question, this is a valuable and interesting problem.

Currently, Aleth-NeRF utilizes the original NeRF to achieve novel view synthesis (NVS), which makes it unsuitable for 360-degree (unbounded) scenes. Currently, I plan to design some low-light enhancement models based on 3D-GS, which may be announced around February or March next year.

**Comment by Sun-Gaust** [comment]
Thank you very much for your reply!
