### ISSUE TITLE
About single image low-light enhancement   

### ISSUE THREAD

**Issue by XLR-man** [cuiziteng/Aleth-NeRF#4]
First of all, thank you very much for your contribution. You stated in the article that this method also works well for low-light enhancement of a single image, thanks to your prior Settings. I would like to ask if there is a single image enhancement code provided.

Using nerf in this paper to do single image low-light enhancement is a bit tedious, because it has to fix the camera pose and other parameters. Have you ever tried using your prior for low-light enhancement of a single image?

**Comment by cuiziteng** [comment]
Hi, thanks for your question, I agree that using NeRF for single image low-light enhancement is tedious, mean-while NeRF is mainly used for novel view synthesis rather than single image. So I may remove this part's experiments in the updated paper version (near future).

**Comment by XLR-man** [comment]
Thank you for your answer

 I have one more question about the code:
```
self.coarse_dark = nn.Parameter(K_g * torch.ones(num_coarse_samples + 1), requires_grad=True) # 65
        self.fine_dark = nn.Parameter(K_g * torch.ones(num_fine_samples + num_coarse_samples + 1), requires_grad=True)  # 193
```
Why do global conceiling field's variables coarse_dark and fine_dark is set to 65 and 193 instead of 64 and 192, and what does the extra value do?

**Comment by cuiziteng** [comment]
Hello, there are no differences between 192/193 and 64/65, just ignore them, also the code and paper have been updated, please refer to the new version.
