### ISSUE TITLE
Depth Image

### ISSUE THREAD

**Issue by linhanwang** [cuiziteng/Aleth-NeRF#6]
Thank you for the outstanding work. I've observed that the depth images in the log directory are in grayscale, whereas those in the paper are colorful. Could you please provide the code or offer some suggestions on how to generate these colorful depth images?

**Comment by cuiziteng** [comment]
Thanks for your interest in our work~  

I've just uploaded a file [depth_trans.py](https://github.com/cuiziteng/Aleth-NeRF/blob/master/depth_trans.py), change to your depth path and you can generate colorful depth images.

**Comment by linhanwang** [comment]
Thank you so much!
