### ISSUE TITLE
RestoreDet

### ISSUE THREAD

**Issue by Liligo** [cuiziteng/Aleth-NeRF#7]
你好，请问RestoreDet这篇文章的源码可以给一份吗？

**Comment by cuiziteng** [comment]
Thanks for your interests, the original RestoreDet has been modified to new version, and there maybe some difference between RestoreDet and New version. Here is the code link: https://github.com/cuiziteng/ECCV_AERIS .

**Comment by Liligo** [comment]
好的，谢谢
