### ISSUE TITLE
render 3D

### ISSUE THREAD

**Issue by zhenyuan1234** [cuiziteng/Aleth-NeRF#8]
Hello, very nice work! I have a question. After testing the model we get 3 image outputs. Can you tell me how to render the 3D motion picture? Thanks!

**Comment by cuiziteng** [comment]
Hi, thanks for your interests, you can direct add " --ginb run.run_render=True" to your inference code. You would get a .mp4 video file in the output folder.

As I mentioned in the README.md ~

<img width="899" alt="image" src="https://github.com/cuiziteng/Aleth-NeRF/assets/55396225/261c5cea-4989-4308-a601-c4c377ebdc57">
