### ISSUE TITLE
Spiral Path for the video

### ISSUE THREAD

**Issue by Vinayak-VG** [cuiziteng/Aleth-NeRF#9]
Hi, Nice work

I wanted to find the code which calculates the poses for rendering the video. I went through the code but was unable to locate it. Would it be possible to please refer me to the section where you are calculating the poses for the path required to render the video?

**Comment by cuiziteng** [comment]
Hi, thanks for your interests, 
the pose to render a video is shown in from here, please check: 

https://github.com/cuiziteng/Aleth-NeRF/blob/758060c3cbd1d37fa6406c542f2a0f9b82fd52df/src/data/data_util/blender.py#L126
